name: Build App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode sumber
        uses: actions/checkout@v4

      - name: Siapkan Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Berikan izin eksekusi
        run: chmod +x gradlew

      - name: Bangun Aplikasi
        run: ./gradlew assembleRelease --warning-mode none

      - name: Simpan Berkas APK
        uses: actions/upload-artifact@v4
        with:
          name: SimpleMusik
          path: app/build/outputs/apk/release/app-release-unsigned.apk
